### PR TITLE
Blog app - Views

### PR DESCRIPTION
**Pull request by gsmalik030**
In This pull request, I completed the following tasks :

- [x] created four views:

1. All users: http://127.0.0.1:3000/users
2. Specific user: http://127.0.0.1:3000/users/1
3. User posts: http://127.0.0.1:3000/users/1/posts
4. Specific post: http://127.0.0.1:3000/users/1/posts/1

- [x] Fix rubocop errors.

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @gsmalik030, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Adds the Views associated with the Models
-  Adds the Views associated and Controllers

## Required Changes ♻️
- [ ] Hi, Nice Job in providing details in your pull request. Unfortunately, the index page is not working. I would advise you to figure out about it, fix it, and submit it again for a second review
- [ ] Suggestion: You can check your migration files, Maybe the mistake is coming from there.

Capture
NB: This comment is not in-line with the concern code because you did make the files visible.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- To Provide a Detailed description of your project in the Readme, This will make your Readme more professional.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gsmalik030** [comment]
Hello @OLIPLICHE 

Thanks for highlighting the error but I am a bit confused when I am running its working perfectly can you please help me with some more information?
Thanks

**Comment by OLIPLICHE** [comment]
Hi, Sorry I closed the review 8 hours ago. I am using my phone to give you this feedback. What I have highlighted is what you can see in the screenshot of your App I pasted. I made a suggestion and I believe you have red it. If you are saying the App is working fine at your end and you are confused based on my Review, then I would advise you to submit it and the next reviewer will check on it.
Thank you for raising up your concern.

**Comment by gsmalik030** [comment]
Thank you @OLIPLICHE 

I found the issue thanks a lot for your suggestion.

**Review by andersonlebon — APPROVED** [review]
## Hi @gsmalik030 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

nodding-yes

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
